{
 "title": "mailcow",
 "tags": [ "mailcow" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_org_label_schema_group=\"mailcow\"})"
    }
   ]
  },
  {
   "title": "Postfix: Mailq",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mailcow_mailq_total" }
   ]
  },
  {
   "title": "Quarantine: Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mailcow_quarantine_total" }
   ]
  },
  {
   "title": "Synjobs: Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mailcow_syncjobs_total" }
   ]
  },
  {
   "title": "Running Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "scalar(count(container_memory_usage_bytes{container_label_org_label_schema_group=\"mailcow\"}) > 0)",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "Rspamd: Total E-Mails",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mailcow_rspamd_total" }
   ]
  },
  {
   "title": "Solr: Total Documents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mailcow_solr_documents_total" }
   ]
  },
  {
   "title": "Domains: Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mailcow_domains_total" }
   ]
  },
  {
   "title": "Mailboxes: Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mailcow_mailboxes_total" }
   ]
  },
  {
   "title": "Mailboxes: Messages Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mailcow_mailboxes_messages_total"
    }
   ]
  },
  {
   "title": "Mailboxes: Total Used Space",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 14, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mailcow_mailboxes_quota_used_total"
    }
   ]
  },
  {
   "title": "Mailboxes: Total Used Space Time Series",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(mailcow_mailboxes_quota_used_total[$__range])"
    }
   ]
  },
  {
   "title": "Mailboxes: Aliases Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mailcow_domains_aliases_total" }
   ]
  },
  {
   "title": "Mails: Time Range",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "increase(mailcow_rspamd_total[$__range])"
    }
   ]
  },
  {
   "title": "Rspamd: No Action Time Range",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(mailcow_rspamd_no_action_total[$__range])"
    }
   ]
  },
  {
   "title": "Rspamd: Add Header  Time Range",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(mailcow_rspamd_add_header_total[$__range])"
    }
   ]
  },
  {
   "title": "Rspamd: Reject  Time Range",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(mailcow_rspamd_reject_total[$__range])"
    }
   ]
  },
  {
   "title": "Rspamd: Soft Reject  Time Range",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(mailcow_rspamd_soft_reject_total[$__range])"
    }
   ]
  },
  {
   "title": "Rspamd",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mailcow_rspamd_add_header_total[$__range])",
     "legendFormat": "Add Header"
    },
    {
     "expr": "increase(mailcow_rspamd_no_action_total[$__range])",
     "legendFormat": "No Action"
    },
    {
     "expr": "increase(mailcow_rspamd_reject_total[$__range])",
     "legendFormat": "Reject"
    },
    {
     "expr": "increase(mailcow_rspamd_rewrite_subject_total[$__range])",
     "legendFormat": "Rewrite Subject"
    },
    {
     "expr": "increase(mailcow_rspamd_soft_reject_total[$__range])",
     "legendFormat": "Soft Reject"
    }
   ]
  },
  { "title": "container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_user_seconds_total{container_label_org_label_schema_group=\"mailcow\"}[1m]) * 100  / scalar(count(node_cpu_seconds_total{mode=\"user\"})))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (container_memory_usage_bytes{container_label_org_label_schema_group=\"mailcow\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{container_label_org_label_schema_group=\"mailcow\"})",
     "legendFormat": "Total memory usage"
    }
   ]
  },
  {
   "title": "Container Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\",container_label_org_label_schema_group=\"mailcow\"}[1m])))* -1",
     "legendFormat": "Outbound: {{ name }}"
    },
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{image!=\"\",container_label_org_label_schema_group=\"mailcow\"}[1m]))",
     "legendFormat": "Inbound: {{ name }}"
    }
   ]
  }
 ]
}